# Generated by Django 5.0.1 on 2024-03-05 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name', models.CharField(max_length=50)),
                ('mothername', models.CharField(max_length=50)),
                ('fathername', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=1)),
                ('address', models.TextField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('reserv', models.CharField(max_length=50)),
                ('classstd', models.IntegerField()),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teach_name', models.CharField(max_length=50)),
                ('teach_mob', models.CharField(max_length=50)),
                ('teach_email', models.CharField(max_length=50)),
                ('teach_dob', models.CharField(max_length=50)),
                ('teach_joingdate', models.CharField(max_length=50)),
                ('teach_address', models.CharField(max_length=50)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('teach_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.department')),
            ],
        ),
    ]
