# Generated by Django 5.0.1 on 2024-02-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name', models.CharField(max_length=50)),
                ('mothername', models.CharField(max_length=50)),
                ('fathername', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=1)),
                ('address', models.TextField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('reserv', models.CharField(max_length=50)),
                ('classstd', models.IntegerField()),
            ],
        ),
    ]
